// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQeRYkhibV31XIfAKYTWKpgEli1zy3KG0',
    appId: '1:566817271141:web:16768fdb7f1801c97c058c',
    messagingSenderId: '566817271141',
    projectId: 'addon2-622ba',
    authDomain: 'addon2-622ba.firebaseapp.com',
    storageBucket: 'addon2-622ba.appspot.com',
    measurementId: 'G-8CGVFBC4GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWsPbs3boa1b93DWaMu6JtYxaMBmv5F_A',
    appId: '1:566817271141:android:cf045e8bf9f0a8d67c058c',
    messagingSenderId: '566817271141',
    projectId: 'addon2-622ba',
    storageBucket: 'addon2-622ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0_pMv6F9ibZfMaEiV2zJbu6aQquJr9uk',
    appId: '1:566817271141:ios:3850b6863bf24a087c058c',
    messagingSenderId: '566817271141',
    projectId: 'addon2-622ba',
    storageBucket: 'addon2-622ba.appspot.com',
    iosBundleId: 'com.example.worksync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0_pMv6F9ibZfMaEiV2zJbu6aQquJr9uk',
    appId: '1:566817271141:ios:7828657bfb6636247c058c',
    messagingSenderId: '566817271141',
    projectId: 'addon2-622ba',
    storageBucket: 'addon2-622ba.appspot.com',
    iosBundleId: 'com.example.worksync.RunnerTests',
  );
}
