import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'choose': 'Choose Language :',
      'languageEn': 'English',
      'languageId': 'Indonesian',
      'languageKr': 'Korean',
      'hello': 'Hello !',
      'helloDesc': 'Welcome to the app to monitor your work activity',
      'login': 'Login',
      'logout': 'Log Out',
      'loginSuccess' : 'Login Successful !',
      'loginSuccessMessage': 'Welcome to the WorkSync App',
      'loginFailed' : 'Login Failed !',
      'loginFailedMessage': 'Try again with your correct account',
      'nameFailed' : 'Save Failed !',
      'nameFailedMessage': 'Name can not be empty',
      'register': 'Register',
      'registerDesc': 'Register to get started !',
      'welcome': 'Welcome !',
      'enterUsername' : 'Username...',
      'enterEmail' : 'Email...',
      'enterPassword' : 'Password...',
      'enterConfirmPassword' : 'Confirm password...',
      'forgotPassword': 'Forgot Password?',
      'anotherLogin' : 'or Login with',
      'anotherRegister' : 'or Register with',
      'dontHaveAccount' : "Don't have an account?",
      'alreadyHaveAccount' : "Already have an account?",
      'scanAttendance' : "SCAN FOR ATTENDANCE",
      'attendance' : "ATTENDANCE",
      'checkIn' : "Check In",
      'checkOut' : "Check Out",
      'late' : "late",
      'onTime' : "on time",
      'seeAll' : "See All",
      'attendanceForm' : "Attendance",
      'attendanceList' : "Attendance List",
      'attendanceFor' : "Attendance For",
      'attendanceType' : "Attendance Type",
      'addCorrection' : "Add Correction",
      'location' : "Location",
      'inTime' : "In Time",
      'in' : "In",
      'out' : "Out",
      'outTime' : "Out Time",
      'correction' : "Correction",
      'correctionFor' : "Correction For",
      'date' : "Date",
      'remark' : "Remark",
      'attachment' : "Attachment",
      'submit' : "Submit",
      'addFile' : "Add File",
      'selectDate' : "Select a Date",
      'faceRecognition' : "Face Recognition",
      'notRecognized' : "not recognized",
      'save' : "Save",
      'request' : "Request",
      'requested' : "Requested",
      'offWork' : "Off Work",
      'overtime' : "Overtime",
      'editOvertime' : "Edit Overtime",
      'overtimeList' : "Overtime List",
      'onDuty' : "On Duty",
      'leave' : "Leave",
      'approvals' : "Approvals",
      'activitiesDesc' : "Add your activities",
      'requestForm' : "Request Form",
      'requestList' : "Request List",
      'requestType' : "Request Type",
      'requestNo' : "Request No",
      'requestFor' : "Request For",
      'addRequest' : "Add Request",
      'addOvertime' : "Add Overtime",
      'name' : "Name",
      'from' : "From",
      'until' : "Until",
      'approve' : "Approve",
      'approved' : "Approved Request",
      'destination' : "Destination",
      'start' : "Start",
      'end' : "End",
      'startTime' : "Select start date",
      'endTime' : "Select end date",
      'onDutyType' : "On Duty Type",
      'overtimeType' : "Overtime Type",
      'offWorkType' : "Off Work Type",
      'leaveType' : "Leave Type",
      'search' : "Search",
      'features' : "FEATURES",
      'payslip' : "Payslip",
      'checkpoinTour' : "Checkpoint Tour",
      'ticketing' : "Ticketing",
      'profile' : "PROFILE",
      'department' : "Department",
      'performance' : "Performance",
      'switchTheme' : "Switch Theme",
      'current' : "Current",
      'language' : "Language",
    },
    'id': {
      'languageEn': 'Inggris',
      'languageId': 'Indonesia',
      'languageKr': 'Korea',
      'choose': 'Pilih Bahasa :',
      'hello': 'Hai !',
      'helloDesc': 'Selamat datang di aplikasi monitoring aktivitas kerja Anda',
      'login': 'Masuk',
      'logout': 'Keluar',
      'loginSuccess' : 'Berhasil Masuk !',
      'loginSuccessMessage': 'Selamat datang di aplikasi WorkSync',
      'loginFailed' : 'Gagal Masuk !',
      'loginFailedMessage': 'Coba lagi dengan akun yang benar',
      'nameFailed' : 'Gagal tersimpan !',
      'nameFailedMessage': 'Nama tidak boleh kosong',
      'register': 'Daftar',
      'registerDesc': 'Daftar untuk memulai !',
      'welcome': 'Selamat Datang !',
      'enterUsername' : 'Username...',
      'enterEmail' : 'Email...',
      'enterPassword' : 'Kata sandi...',
      'enterConfirmPassword' : 'Konfirmasi kata sandi...',
      'forgotPassword': 'Lupa kata sandi?',
      'anotherLogin' : 'atau Masuk dengan',
      'anotherRegister' : 'atau Daftar dengan',
      'dontHaveAccount' : "Belum memiliki akun?",
      'alreadyHaveAccount' : "Sudah memiliki akun?",
      'scanAttendance' : "DETEKSI UNTUK ABSEN",
      'attendance' : "KEHADIRAN",
      'checkIn' : "Masuk",
      'checkOut' : "Pulang",
      'late' : "telat",
      'onTime' : "tepat waktu",
      'seeAll' : "Lihat Semua",
      'attendanceForm' : "Kehadiran",
      'attendanceList' : "Daftar Kehadiran",
      'attendanceFor' : "Kehadiran untuk",
      'attendanceType' : "Tipe Kehadiran",
      'addCorrection' : "Koreksi Kehadiran",
      'location' : "Lokasi",
      'inTime' : "Waktu Masuk",
      'in' : "Masuk",
      'out' : "Pulang",
      'outTime' : "Waktu Pulang",
      'correction' : "Koreksi Kehadiran",
      'correctionFor' : "Koreksi untuk",
      'date' : "Tanggal",
      'remark' : "Keterangan",
      'attachment' : "Lampiran",
      'submit' : "Kirim",
      'addFile' : "Tambah Berkas",
      'selectDate' : "Pilih Tanggal",
      'faceRecognition' : "Deteksi Wajah",
      'notRecognized' : "Tidak dikenali",
      'save' : "Simpan",
      'request' : "PERMOHONAN",
      'requested' : "Diajukan",
      'offWork' : "Cuti",
      'overtime' : "Lembur",
      'editOvertime' : "Ubah Lembur",
      'overtimeList' : "Daftar Lembur",
      'onDuty' : "Bertugas",
      'leave' : "Izin Keluar",
      'approvals' : "Persetujuan",
      'activitiesDesc' : "Tambahkan aktivitas Anda",
      'requestForm' : "Permohonan",
      'requestList' : "Daftar Permohonan",
      'requestType' : "Tipe",
      'requestNo' : "Nomor",
      'requestFor' : "Permohonan untuk",
      'addRequest' : "Tambah Permohonan",
      'addOvertime' : "Tambah Lembur",
      'name' : "Nama",
      'from' : "Dari",
      'until' : "Sampai",
      'approve' : "Setujui",
      'approved' : "Permohonan Diakui",
      'destination' : "Destinasi",
      'start' : "Mulai",
      'end' : "Selesai",
      'startTime' : "Tanggal mulai",
      'endTime' : "Tanggal selesai",
      'onDutyType' : "Tipe Bertugas",
      'overtimeType' : "Tipe Lembur",
      'offWorkType' : "Tipe Cuti",
      'leaveType' : "Tipe Izin Keluar",
      'search' : "Cari",
      'features' : "FITUR - FITUR",
      'payslip' : "Slip Gaji",
      'checkpoinTour' : "Pemeriksaan",
      'ticketing' : "Sistem Tiket",
      'profile' : "PROFIL",
      'department' : "Departemen",
      'performance' : "Performa",
      'switchTheme' : "Ganti Tema",
      'current' : "Saat Ini",
      'language' : "Bahasa",
    },
    'ko': {
      'languageEn': '영어 (Eng)',
      'languageId': '인도네시아 (Ina)',
      'languageKr': '한국',
      'choose': '언어 선택 :',
      'hello': '안녕하세요 !',
      'helloDesc': '일하다 활동 모니터링하는 앱에 오신 것을 환영합니다',
      'login': '로그인',
      'logout': '로그 아웃',
      'loginSuccess' : '로그인 성공 !',
      'loginSuccessMessage': 'WorkSync앱에 환영합니다',
      'loginFailed' : '로그인 실패 !',
      'loginFailedMessage': '다른 계정으로 다시 시도하세요',
      'nameFailed' : '저장에 실패했습니다 !',
      'nameFailedMessage': '이름은 비워둘 수 없습니다',
      'register': '회원가입',
      'registerDesc': '시작하려면 회원가입하세요 !',
      'welcome': '환영합니다 !',
      'enterUsername' : '아이디...',
      'enterEmail' : '이메일...',
      'enterPassword' : '비밀번호...',
      'enterConfirmPassword' : '비밀번호 확인...',
      'forgotPassword': '비밀번호 찾기?',
      'anotherLogin' : '다른 로그인',
      'anotherRegister' : '다른 회원가입',
      'dontHaveAccount' : "계정이 없는 경우?",
      'alreadyHaveAccount' : "이미 계정니 있습니다?",
      'scanAttendance' : "출석 스캔",
      'attendance' : "출석",
      'checkIn' : "체크 인",
      'checkOut' : "체크 아웃",
      'late' : "늦어서",
      'onTime' : "정시에",
      'seeAll' : "모두 보기",
      'attendanceForm' : "출석",
      'attendanceList' : "출석 목록",
      'attendanceFor' : "사영자 출석",
      'attendanceType' : "출석 유형",
      'addCorrection' : "수정 추가",
      'location' : "위치",
      'inTime' : "입장 후",
      'in' : "인",
      'out' : "아웃",
      'outTime' : "퇴근 후",
      'correction' : "수정",
      'correctionFor' : "사용자 수정",
      'date' : "날자 선택",
      'remark' : "설명",
      'attachment' : "첨부 파일",
      'submit' : "보내",
      'addFile' : "파일 추가",
      'selectDate' : "날짜를 선택하세요",
      'faceRecognition' : "얼굴 인식",
      'notRecognized' : "얼굴이 인식되지 않음",
      'save' : "저장",
      'request' : "요구",
      'requested' : "요청됨",
      'offWork' : "유급 휴가",
      'overtime' : "초과 근무",
      'editOvertime' : "초과 근무 수정",
      'overtimeList' : "초과 근무 목록",
      'onDuty' : "근무 시간",
      'leave' : "일찍 퇴근",
      'approvals' : "승인",
      'activitiesDesc' : "활동을 추가하세요",
      'requestForm' : "요구",
      'requestList' : "요구 목록",
      'requestType' : "요구 유형",
      'requestNo' : "요구 번허",
      'requestFor' : "요구 사용자",
      'addRequest' : "요구 추가",
      'addOvertime' : "초과 근무 추가",
      'name' : "이름",
      'from' : "시작",
      'until' : "까지",
      'approve' : "승인하다",
      'approved' : "승인된 요구",
      'destination' : "목적지",
      'start' : "시작",
      'end' : "끝",
      'startTime' : "시작 날짜 선택",
      'endTime' : "종료일을 선택",
      'onDutyType' : "근무 시간 유형",
      'overtimeType' : "초과 근무 유형 ",
      'offWorkType' : "유급 휴가 유형",
      'leaveType' : "일찍 퇴근 유형",
      'search' : "검색",
      'features' : "특징",
      'payslip' : "직원 급여",
      'checkpoinTour' : "체크포인 투어",
      'ticketing' : "발권",
      'profile' : "프로필",
      'department' : "부서",
      'performance' : "성과",
      'switchTheme' : "테마 변경",
      'current' : "지금",
      'language' : "언어",
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}
